// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_appsync_graphqlEndpoint": "https://r3iifmnwmnbwxncqlaadzwzyla.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-koopb7inxverbhb2kuteszwgr4",
    "aws_cognito_identity_pool_id": "eu-north-1:43e726b4-618d-45e6-95d8-be215c6856b6",
    "aws_user_pools_id": "eu-north-1_YjxKPhYJR",
    "aws_user_pools_web_client_id": "3q63caftpstni68tm96esv30j8",

    "oauth": {
        // "domain": "https://main.d1a8guazubpch4.amplifyapp.com/",
        "domain": "http://localhost:3000/",
        "scope": ["email", "openid", "aws.cognito.signin.user.admin"],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code" // or 'token', depending on your flow
    }

};


// ros.kichuk@gmail.com
// Qwerty12345.!

export default awsmobile;